### ISSUE TITLE
Access log is not working

### ISSUE THREAD

**Issue by deeky666** [symfony-swoole/swoole-bundle#147]
**Describe the bug**
I tried to enable the `access_log` feature in a Symfony environment but it does not work because `SwooleExtension.php` does not set the required argument `$accessLogLogger` in the constructor of `AccessLogOnKernelTerminate`.

![image](https://github.com/user-attachments/assets/8bd1d44e-5eb1-4700-9ccf-bbb627e01438)

![image](https://github.com/user-attachments/assets/d36c06c5-bc2f-45e8-9e5a-394447c166c4)

**Steps To Reproduce**
Enable `access_log` config. The server throws `SwooleBundle\SwooleBundle\Bridge\Symfony\HttpFoundation\AccessLogOnKernelTerminate::__construct(): Argument #1 ($accessLogLogger) not passed` when trying to write the log.

**Expected behavior**
No exception, it just works.

**Environment (please complete the following information):**
 - OS:Linux
 - PHP Version: 8.3.14
 - Swoole Version: openswoole-22.1.2
 - Symfony Version: 7.1.6
 - Running in docker: Yes

**Additional context**
None

**Logs**
If possible/applicable please provide symfony/swoole logs here.

<details><summary>Symfony/Swoole Logs</summary>
<p>

```
Fatal error: Uncaught ErrorException: Warning: OpenSwoole\Http\Response::header(): http response is unavailable (maybe it has been ended or detached) in /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionHandler/JsonExceptionHandler.php:24
Stack trace:
#0 /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionRequestHandler.php(24): SwooleBundle\SwooleBundle\Server\RequestHandler\ExceptionHandler\JsonExceptionHandler->handle(Object(OpenSwoole\Http\Request), Object(ArgumentCountError), Object(OpenSwoole\Http\Response))
#1 [internal function]: SwooleBundle\SwooleBundle\Server\RequestHandler\ExceptionRequestHandler->handle(Object(OpenSwoole\Http\Request), Object(OpenSwoole\Http\Response))
#2 {main}
  thrown in /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionHandler/JsonExceptionHandler.php on line 24
Symfony\Component\ErrorHandler\Error\FatalError {#11830
  #message: """
    Error: Uncaught ErrorException: Warning: OpenSwoole\Http\Response::header(): http response is unavailable (maybe it has been ended or detached) in /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionHandler/JsonExceptionHandler.php:24\n
    Stack trace:\n
    #0 /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionRequestHandler.php(24): SwooleBundle\SwooleBundle\Server\RequestHandler\ExceptionHandler\JsonExceptionHandler->handle(Object(OpenSwoole\Http\Request), Object(ArgumentCountError), Object(OpenSwoole\Http\Response))\n
    #1 [internal function]: SwooleBundle\SwooleBundle\Server\RequestHandler\ExceptionRequestHandler->handle(Object(OpenSwoole\Http\Request), Object(OpenSwoole\Http\Response))\n
    #2 {main}\n
      thrown
    """
  #code: 0
  #file: "./vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionHandler/JsonExceptionHandler.php"
  #line: 24
  -error: array:4 [
    "type" => 1
    "message" => """
      Uncaught ErrorException: Warning: OpenSwoole\Http\Response::header(): http response is unavailable (maybe it has been ended or detached) in /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionHandler/JsonExceptionHandler.php:24\n
      Stack trace:\n
      #0 /app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionRequestHandler.php(24): SwooleBundle\SwooleBundle\Server\RequestHandler\ExceptionHandler\JsonExceptionHandler->handle(Object(OpenSwoole\Http\Request), Object(ArgumentCountError), Object(OpenSwoole\Http\Response))\n
      #1 [internal function]: SwooleBundle\SwooleBundle\Server\RequestHandler\ExceptionRequestHandler->handle(Object(OpenSwoole\Http\Request), Object(OpenSwoole\Http\Response))\n
      #2 {main}\n
        thrown
      """
    "file" => "/app/vendor/swoole-bundle/swoole-bundle/src/Server/RequestHandler/ExceptionHandler/JsonExceptionHandler.php"
    "line" => 24
  ]
}

Fatal error: Uncaught OpenSwoole\ExitException: swoole exit in /app/vendor/symfony/error-handler/ErrorHandler.php:641
Stack trace:
#0 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler::Symfony\Component\ErrorHandler\{closure}()
#1 {main}
  thrown in /app/vendor/symfony/error-handler/ErrorHandler.php on line 641
[2024-11-29 19:47:52 *172.0]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught OpenSwoole\ExitException: swoole exit in /app/vendor/symfony/error-handler/ErrorHandler.php:641
Stack trace:
#0 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler::Symfony\Component\ErrorHandler\{closure}()
#1 {main}
  thrown in /app/vendor/symfony/error-handler/ErrorHandler.php on line 641
[2024-11-29 19:47:52 $170.0]	WARNING	Server::check_worker_exit_status(): worker(pid=172, id=0) abnormal exit, status=255, signal=0
```

</p>
</details>

**Comment by pistej** [comment]
You need to set monolog handler, symfony will create service/alias with this name for autoloading, smth like this:
```
monolog:
  handlers:
      swoole_access_log:
        type: stream
        path: "php://stderr"
        level: info
```
see odcs: https://github.com/symfony-swoole/swoole-bundle/blob/develop/docs/swoole-access-logs.md

**Comment by deeky666** [comment]
Ah I see, it was not clear to me that I have to use monolog. I thought it would be possible without installing monolog. Fine. Closing then :)

Thank you!

**Comment by pistej** [comment]
This bundle already have monolog installed,  (see composer require section) ... but you dont have to use it,  you can use any logging library with PSR3 support and configure it with Symfony to autoload it as  `LoggerInterface $accessLogLogger`
